# Generated by Django 5.2 on 2025-04-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(blank=True, default='[]', verbose_name='Содержимое заказа'),
        ),
    ]
